<nav class="navbar bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="Skin/css/download.png" width="50" class="rounded">
        </a>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link active m-4 mx-2" aria-current="page" href="index.php?c=product&a=grid">Product</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active m-4 mx-2" aria-current="page" href="index.php?c=category&a=grid">Category</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active m-4 mx-2" aria-current="page" href="index.php?c=customer&a=grid">Customer</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active m-4 mx-2" aria-current="page" href="index.php?c=vendor&a=grid">Vendor</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active m-4 mx-2" aria-current="page" href="index.php?c=salesman&a=grid">Salesman</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link active m-4 mx-2" aria-current="page" href="index.php?c=shipping&a=grid">Shipping</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active m-4 mx-2" aria-current="page" href="index.php?c=payment&a=grid">Payment</a>
            </li> -->
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle m-4 mx-2" data-bs-toggle="dropdown" role="button" aria-expanded="false">Dropdown</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="index.php?c=eav_attribute&a=grid">EAV Attribute</a></li>
                    <li><a class="dropdown-item" href="#"></a></li>
                    <li><a class="dropdown-item" href="#"></a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#"></a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>