<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Product Edit</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>
	<?php require_once 'view/html/header.phtml'; ?>

	<div class="container m-4">		
		<div class="d-flex justify-content-between">
			<h3>Edit Products</h3>
			<div class="d-grid gap-2 d-md-flex justify-content-md-end">
		 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button" href="index.php?c=product&a=grid">Cancel</a>
			</div>
		</div>

		<form method="post" action="index.php?c=product&a=update&id=<?php echo $product['product_id']; ?>">
			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
				<div class="col-sm-10">
					<input type="text" name="name" class="form-control" value="<?php echo $product['name'] ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">SKU</label>
				<div class="col-sm-10">
					<input type="text" name="sku" class="form-control" value="<?php echo $product['sku'] ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Cost</label>
				<div class="col-sm-10">
					<input type="text" name="cost" class="form-control" value="<?php echo $product['cost'] ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Price</label>
				<div class="col-sm-10">
					<input type="text" name="price" class="form-control" value="<?php echo $product['price'] ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Quantity</label>
				<div class="col-sm-10">
					<input type="text" name="quantity" class="form-control" value="<?php echo $product['quantity'] ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Description</label>
				<div class="col-sm-10">
					<textarea name="description" class="form-control" cols="60" rows="3"><?php echo $product['description'] ?>
					</textarea>
				</div>
			</div>

			<fieldset class="row mb-3">
				<legend class="col-form-label col-sm-2 pt-0">Status</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<select name="status" class="form-select" aria-label="Default select example">
							<option value="1">active</option>
							<option value="2">inactive</option>
						</select>
					</div>
				</div>
			</fieldset>

			<fieldset class="row mb-3">
				<legend class="col-form-label col-sm-2 pt-0">Color</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<select name="color" class="form-select" aria-label="Default select example">
							<option value="red">red</option>
							<option value="green">green</option>
						</select>
					</div>
				</div>
			</fieldset>

			<fieldset class="row mb-3">
				<legend class="col-form-label col-sm-2 pt-0">Material</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<select name="material" class="form-select" aria-label="Default select example">
							<option value="soft">soft</option>
							<option value="hard">hard</option>
						</select>
					</div>
				</div>
			</fieldset>

			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>

	<?php require_once 'view/html/footer.phtml'; ?>
</body>
</html>