<?php $product = $this->getRow(); ?>
<div class="container m-4">		
	<div class="d-flex justify-content-between">
		<h3>Save Products</h3>
		<div class="d-grid gap-2 d-md-flex justify-content-md-end">
	 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button" href="index.php?c=product&a=grid">Cancel</a>
		</div>
	</div>
	<form method="post" action="index.php?c=product&a=save&id=<?php echo $product->product_id;; ?>">
		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
			<div class="col-sm-10">
				<input type="text" name="product[name]" class="form-control" value="<?php echo $product->name; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">SKU</label>
			<div class="col-sm-10">
				<input type="text" name="product[sku]" class="form-control" value="<?php echo $product->sku; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Cost</label>
			<div class="col-sm-10">
				<input type="text" name="product[cost]" class="form-control" value="<?php echo $product->cost; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Price</label>
			<div class="col-sm-10">
				<input type="text" name="product[price]" class="form-control" value="<?php echo $product->price; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Quantity</label>
			<div class="col-sm-10">
				<input type="text" name="product[quantity]" class="form-control" value="<?php echo $product->quantity; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Description</label>
			<div class="col-sm-10">
				<textarea name="product[description]" class="form-control" cols="60" rows="3"><?php echo $product->description; ?></textarea>
			</div>
		</div>

		<fieldset class="row mb-3">
			<legend class="col-form-label col-sm-2 pt-0">Status</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<select name="product[status]" class="form-select" aria-label="Default select example">
						<?php foreach($product->getResource()->getStatusOptions() as $key => $value): ?>
						<?php $selected = ($key == $product->getStatus()) ? 'selected' : '' ?>
							<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
		</fieldset>

		<fieldset class="row mb-3">
			<legend class="col-form-label col-sm-2 pt-0">Color</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<select name="product[color]" class="form-select" aria-label="Default select example">
						<option value="red" <?php if ($product->color === 'red') { echo "selected";} ?>> red </option>
						<option value="green" <?php if ($product->color === 'green') { echo "selected"; } ?>> green </option>
					</select>
				</div>
			</div>
		</fieldset>

		<fieldset class="row mb-3">
			<legend class="col-form-label col-sm-2 pt-0">Material</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<select name="product[material]" class="form-select" aria-label="Default select example">
						<option value="hard" <?php if ($product->material === 'hard') {echo "selected";} ?>> hard </option>
						<option value="soft" <?php if ($product->material === 'soft') {echo "selected";} ?>> soft </option>
					</select>
				</div>
			</div>
		</fieldset>

		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>