<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Product Grid</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>

	<?php require_once 'view/html/header.phtml'; ?>

	<div class="container">		
	<div class="d-flex justify-content-between">
		<h3>Manage Products</h3>
		<div class="d-grid gap-2 d-md-flex justify-content-md-end">
	 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button" href="index.php?c=product&a=add">Add Product</a>
		</div>
	</div>

	<table class="table table-bordered table-success table-striped w-100">
		<thead>
			<tr>
				<th>Product Id</th>
				<th>Name</th>
				<th>SKU</th>
				<th>Cost</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Description</th>
				<th>Status</th>
				<th>Color</th>
				<th>Material</th>
				<th>Small Id</th>
				<th>Thumbnail Id</th>
				<th>Base Id</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<?php foreach ($products as $product) : ?>
		<tbody>
			<tr>
				<td><?php echo $product['product_id']; ?></td>
				<td><?php echo $product['name']; ?></td>
				<td><?php echo $product['sku']; ?></td>
				<td><?php echo $product['cost']; ?></td>
				<td><?php echo $product['price']; ?></td>
				<td><?php echo $product['quantity']; ?></td>
				<td><?php echo $product['description']; ?></td>
				<td><?php echo $product['status']; ?></td>
				<td><?php echo $product['color']; ?></td>
				<td><?php echo $product['material']; ?></td>
				<td><?php echo $product['small_id']; ?></td>
				<td><?php echo $product['thumbnail_id']; ?></td>
				<td><?php echo $product['base_id']; ?></td>
				<td>Media</td>
				<td><a href="index.php?c=product&a=edit&id=<?php echo $product['product_id']; ?>">Edit</a></td>
				<td><a href="index.php?c=product&a=delete&id=<?php echo $product['product_id']; ?>">Delete</a></td>
			</tr>
		</tbody>
		<?php endforeach; ?>
	</table>

	<?php require_once 'view/html/footer.phtml'; ?>
</body>
</html>

