<?php
$attribute = $this->getAttribute();
$row = $this->getRow();

$options = $attribute->getOptions();
$optionsValue = $row->getAttributeValue($attribute);
if ($optionsValue) {
	$optionsValue = explode(",", $optionsValue);
}
?>

<fieldset class="row mb-3">
	<div class="col-sm-15">
		<div class="form-check">
			<select class="form-select" name="attribute[<?php echo $attribute->backend_type ?>][<?php echo $attribute->getId() ?>]" multiple>
				<?php if($options): ?>
					<?php foreach($options->getData() as $option) : ?>
						<?php $selected = ''; 
						if ($optionsValue) {
							$selected = (in_array($option->option_id, $optionsValue)) ? 'selected':'';
						} ?>

						<option value="<?php echo $option->option_id ?>"<?php echo $selected; ?>>
							<?php echo $option->name; ?>				
						</option>
					<?php endforeach; ?>
				<?php endif; ?>
			</select>
		</div>
	</div>
</fieldset>
