<!DOCTYPE html>
<html>
<?php echo $this->getChildHtml('head'); ?>
<body>
	<table class="table  table-bordered  border-dark w-100 mx-auto">
		<tr>
			<td colspan="3"><?php echo $this->getChildHtml('header'); ?></td>
		</tr>
		<tr>
			<td colspan="3" id="message-html"><?php echo $this->getChildHtml('message'); ?></td>
		</tr>
		<tr>
			<td><?php echo $this->getChildHtml('left'); ?></td>
			<td><?php echo $this->getChildHtml('content'); ?></td>
			<td><?php echo $this->getChildHtml('right'); ?></td>
		</tr>
		<tr class="mx-0">
			<td colspan="3"><?php echo $this->getChildHtml('footer'); ?></td>
		</tr>
	</table>
</body>
</html>