<?php 
$customer = $this->customer;
$billingAddress = $this->billingAddress;
$shippingAddress = $this->shippingAddress;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Customer Edit</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>
	<?php require_once 'view/html/header.phtml'; ?>

	<div class="container m-4">		
		<div class="d-flex justify-content-between">
			<h3>Edit Customer</h3>
			<div class="d-grid gap-2 d-md-flex justify-content-md-end">
		 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button"  href="index.php?c=customer&a=grid">Cancel</a>
			</div>
		</div>

		<form method="post" action="index.php?c=customer&a=save&id=<?php echo $customer->customer_id; ?>">
			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">First Name</label>
				<div class="col-sm-10">
					<input type="text" name="customer[first_name]" class="form-control" value="<?php echo $customer->first_name; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Last Name</label>
				<div class="col-sm-10">
					<input type="text" name="customer[last_name]" class="form-control" value="<?php echo $customer->last_name; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Email</label>
				<div class="col-sm-10">
					<input type="text" name="customer[email]" class="form-control" value="<?php echo $customer->email; ?>">
				</div>
			</div>

			<fieldset class="row mb-3">
				<legend class="col-form-label col-sm-2 pt-0">Color</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<select name="customer[gender]" class="form-select" aria-label="Default select example">
							<option value="male" <?php if ($customer->gender === 'male') { echo "selected";} ?>> male </option>
    						<option value="female" <?php if ($customer->gender === 'female') { echo "selected"; } ?>> female </option>
						</select>
					</div>
				</div>
			</fieldset>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Mobile</label>
				<div class="col-sm-10">
					<input type="text" name="customer[mobile]" class="form-control" value="<?php echo $customer->mobile; ?>">
				</div>
			</div>

			<fieldset class="row mb-3">
				<legend class="col-form-label col-sm-2 pt-0">Status</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<select name="customer[status]" class="form-select" aria-label="Default select example">
							<?php foreach($customer->getTable()->getStatusOptions() as $key => $value): ?>
							<?php $selected = ($key == $customer->getStatus()) ? 'selected' : '' ?>
								<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</fieldset>

			<h3 class="m-5 mx-0">Billing Address Information</h3>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Address</label>
				<div class="col-sm-10">
					<input type="text" name="billingAddress[address]" class="form-control" value="<?php echo $billingAddress->address; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">City</label>
				<div class="col-sm-10">
					<input type="text" name="billingAddress[city]" class="form-control" value="<?php echo $billingAddress->city; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">State</label>
				<div class="col-sm-10">
					<input type="text" name="billingAddress[state]" class="form-control" value="<?php echo $billingAddress->state; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Country</label>
				<div class="col-sm-10">
					<input type="text" name="billingAddress[country]" class="form-control" value="<?php echo $billingAddress->country; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Zip Code</label>
				<div class="col-sm-10">
					<input type="text" name="billingAddress[zipcode]" class="form-control" value="<?php echo $billingAddress->zipcode; ?>">
				</div>
			</div>


			<h3 class="m-5 mx-0">Shipping Address Information</h3>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Address</label>
				<div class="col-sm-10">
					<input type="text" name="shippingAddress[address]" class="form-control" value="<?php echo $shippingAddress->address; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">City</label>
				<div class="col-sm-10">
					<input type="text" name="shippingAddress[city]" class="form-control" value="<?php echo $shippingAddress->city; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">State</label>
				<div class="col-sm-10">
					<input type="text" name="shippingAddress[state]" class="form-control" value="<?php echo $shippingAddress->state; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Country</label>
				<div class="col-sm-10">
					<input type="text" name="shippingAddress[country]" class="form-control" value="<?php echo $shippingAddress->country; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Zip Code</label>
				<div class="col-sm-10">
					<input type="text" name="shippingAddress[zipcode]" class="form-control" value="<?php echo $shippingAddress->zipcode; ?>">
				</div>
			</div>
			

			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>

	<?php require_once 'view/html/footer.phtml'; ?>
</body>
</html>