<?php 
$allData = $this->getRow();
$customer = $allData[0];
$billingAddress = $allData[1];
$shippingAddress = $allData[2];
?>
<div class="container m-4">		
	<div class="d-flex justify-content-between">
		<h3>Save Customer</h3>
		<div class="d-grid gap-2 d-md-flex justify-content-md-end">
	 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button"  href="index.php?c=customer&a=grid">Cancel</a>
		</div>
	</div>

	<form method="post" action="index.php?c=customer&a=save&id=<?php echo $customer->customer_id; ?>">
		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">First Name</label>
			<div class="col-sm-10">
				<input type="text" name="customer[first_name]" class="form-control" value="<?php echo $customer->first_name; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Last Name</label>
			<div class="col-sm-10">
				<input type="text" name="customer[last_name]" class="form-control" value="<?php echo $customer->last_name; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Email</label>
			<div class="col-sm-10">
				<input type="text" name="customer[email]" class="form-control" value="<?php echo $customer->email; ?>">
			</div>
		</div>

		<fieldset class="row mb-3">
			<legend class="col-form-label col-sm-2 pt-0">Color</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<select name="customer[gender]" class="form-select" aria-label="Default select example">
						<option value="male" <?php if ($customer->gender === 'male') { echo "selected";} ?>> male </option>
						<option value="female" <?php if ($customer->gender === 'female') { echo "selected"; } ?>> female </option>
					</select>
				</div>
			</div>
		</fieldset>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Mobile</label>
			<div class="col-sm-10">
				<input type="text" name="customer[mobile]" class="form-control" value="<?php echo $customer->mobile; ?>">
			</div>
		</div>

		<fieldset class="row mb-3">
			<legend class="col-form-label col-sm-2 pt-0">Status</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<select name="customer[status]" class="form-select" aria-label="Default select example">
						<?php foreach($customer->getResource()->getStatusOptions() as $key => $value): ?>
						<?php $selected = ($key == $customer->getStatus()) ? 'selected' : '' ?>
							<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
		</fieldset>

		<h3 class="m-5 mx-0">Billing Address Information</h3>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Address</label>
			<div class="col-sm-10">
				<input type="text" name="billingAddress[address]" class="form-control" value="<?php echo $billingAddress->address; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">City</label>
			<div class="col-sm-10">
				<input type="text" name="billingAddress[city]" class="form-control" value="<?php echo $billingAddress->city; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">State</label>
			<div class="col-sm-10">
				<input type="text" name="billingAddress[state]" class="form-control" value="<?php echo $billingAddress->state; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Country</label>
			<div class="col-sm-10">
				<input type="text" name="billingAddress[country]" class="form-control" value="<?php echo $billingAddress->country; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Zip Code</label>
			<div class="col-sm-10">
				<input type="text" name="billingAddress[zipcode]" class="form-control" value="<?php echo $billingAddress->zipcode; ?>">
			</div>
		</div>


		<h3 class="m-5 mx-0">Shipping Address Information</h3>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Address</label>
			<div class="col-sm-10">
				<input type="text" name="shippingAddress[address]" class="form-control" value="<?php echo $shippingAddress->address; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">City</label>
			<div class="col-sm-10">
				<input type="text" name="shippingAddress[city]" class="form-control" value="<?php echo $shippingAddress->city; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">State</label>
			<div class="col-sm-10">
				<input type="text" name="shippingAddress[state]" class="form-control" value="<?php echo $shippingAddress->state; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Country</label>
			<div class="col-sm-10">
				<input type="text" name="shippingAddress[country]" class="form-control" value="<?php echo $shippingAddress->country; ?>">
			</div>
		</div>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Zip Code</label>
			<div class="col-sm-10">
				<input type="text" name="shippingAddress[zipcode]" class="form-control" value="<?php echo $shippingAddress->zipcode; ?>">
			</div>
		</div>
		

		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>