<?php $final = $this->getRow(); ?>
<?php $category = $final[0]; ?>
<?php $pathCategories = $final[1]; ?>
<?php $attributes = $this->getAttribute(); ?>
<div class="container m-4">		
	<div class="d-flex justify-content-between">
		<h3>Edit Category</h3>
		<div class="d-grid gap-2 d-md-flex justify-content-md-end">
	 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button" href="<?php echo $this->getUrl('grid', 'category') ?>">Cancel</a>
		</div>
	</div>

	<form method="post" action="index.php?c=category&a=save&id=<?php echo $category->category_id;; ?>">
		<fieldset class="row mb-3">
			<legend class="col-form-label col-sm-2 pt-0">Parent Category</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<select name="category[parent_id]" class="form-select" aria-label="Default select example">
						<?php foreach($pathCategories as $category_id => $path): ?>
						<?php $selected = ($category_id == $category->parent_id) ? 'selected' : '' ?>
							<option value="<?php echo $category_id ?>" <?php echo $selected; ?>><?php echo $category->getPathCategories($category_id) ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
		</fieldset>

		<div class="row mb-3">
			<label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
			<div class="col-sm-10">
				<input type="text" name="category[name]" class="form-control" value="<?php echo $category->name; ?>">
			</div>
		</div>

		<fieldset class="row mb-3">
			<legend class="col-form-label col-sm-2 pt-0">Status</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<select name="category[status]" class="form-select" aria-label="Default select example">
						<?php foreach($category->getResource()->getStatusOptions() as $key => $value): ?>
						<?php $selected = ($key == $category->getStatus()) ? 'selected' : '' ?>
							<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
		</fieldset>

		<div class="row mb-3">
			<label for="inputPassword3" class="col-sm-2 col-form-label">Description</label>
			<div class="col-sm-10">
				<textarea name="category[description]" class="form-control" cols="60" rows="3"><?php echo $category->description; ?></textarea>
			</div>
		</div>

		<div class="row mb-3">
		<?php foreach($attributes as $key => $attribute) : ?>
			<label for="inputPassword3" class="col-sm-2 col-form-label"><?php echo $attribute->name; ?></label>
			<div class="col-sm-10">
				<?php echo $this->getLayout()
							->createBlock('Core_Eav_Attribute_InputType')
							->setAttribute($attribute)
							->setRow($category)
							->toHtml(); ?>
			</div>
		<?php endforeach; ?>
		</div>

		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>