<?php $categorys = $this->categorys; ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Category Grid</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>

	<?php require_once 'view/html/header.phtml'; ?>

	<div class="container">		
	<div class="d-flex justify-content-between">
		<h3>Manage Categorys</h3>
		<div class="d-grid gap-2 d-md-flex justify-content-md-end">
	 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button" href="index.php?c=category&a=add">Add Category</a>
		</div>
	</div>

	<table class="table table-bordered table-success table-striped w-100">
		<thead>
			<tr>
				<th>Category Id</th>
				<th>Name</th>
				<th>Status</th>
				<th>Description</th>
				<th>Create_At</th>
				<th>Update_At</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<?php foreach ($categorys as $category) : ?>
		<tbody>
			<tr>
				<td><?php echo $category->category_id; ?></td>
				<td><?php echo $category->name; ?></td>
				<td><?php echo $category->getStatusText($category->status); ?></td>
				<td><?php echo $category->description; ?></td>
				<td><?php echo $category->create_at; ?></td>
				<td><?php echo $category->update_at; ?></td>
				<td><a href="index.php?c=category&a=edit&id=<?php echo $category->category_id; ?>">Edit</a></td>
				<td><a href="index.php?c=category&a=delete&id=<?php echo $category->category_id; ?>">Delete</a></td>
			</tr>
		</tbody>
		<?php endforeach; ?>
	</table>

	<?php require_once 'view/html/footer.phtml'; ?>
</body>
</html>