<?php 
$salesman = $this->salesman;
$address = $this->address;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Salesman Edit</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>
	<?php require_once 'view/html/header.phtml'; ?>

	<div class="container m-4">		
		<div class="d-flex justify-content-between">
			<h3>Edit Salesman</h3>
			<div class="d-grid gap-2 d-md-flex justify-content-md-end">
		 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button"  href="index.php?c=salesman&a=grid">Cancel</a>
			</div>
		</div>

		<form method="post" action="index.php?c=salesman&a=save&id=<?php echo $salesman->salesman_id; ?>">
			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">First Name</label>
				<div class="col-sm-10">
					<input type="text" name="salesman[first_name]" class="form-control" value="<?php echo $salesman->first_name; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Last Name</label>
				<div class="col-sm-10">
					<input type="text" name="salesman[last_name]" class="form-control" value="<?php echo $salesman->last_name; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Email</label>
				<div class="col-sm-10">
					<input type="text" name="salesman[email]" class="form-control" value="<?php echo $salesman->email; ?>">
				</div>
			</div>

			<fieldset class="row mb-3">
				<legend class="col-form-label col-sm-2 pt-0">Color</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<select name="salesman[gender]" class="form-select" aria-label="Default select example">
							<option value="male" <?php if ($salesman->gender === 'male') { echo "selected";} ?>> male </option>
    						<option value="female" <?php if ($salesman->gender === 'female') { echo "selected"; } ?>> female </option>
						</select>
					</div>
				</div>
			</fieldset>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Mobile</label>
				<div class="col-sm-10">
					<input type="text" name="salesman[mobile]" class="form-control" value="<?php echo $salesman->mobile; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputPassword3" class="col-sm-2 col-form-label">Company</label>
				<div class="col-sm-10">
					<input type="text" name="salesman[company]" class="form-control" value="<?php echo $salesman->company; ?>">
				</div>
			</div>

			<fieldset class="row mb-3">
				<legend class="col-form-label col-sm-2 pt-0">Status</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<select name="salesman[status]" class="form-select" aria-label="Default select example">
							<?php foreach($salesman->getTable()->getStatusOptions() as $key => $value): ?>
							<?php $selected = ($key == $salesman->getStatus()) ? 'selected' : '' ?>
								<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value; ?></option>
								<option value="2">inactive</option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</fieldset>

			<h3 class="m-5 mx-0">Address Information</h3>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Address</label>
				<div class="col-sm-10">
					<input type="text" name="address[address]" class="form-control" value="<?php echo $address->address; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">City</label>
				<div class="col-sm-10">
					<input type="text" name="address[city]" class="form-control" value="<?php echo $address->city; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">State</label>
				<div class="col-sm-10">
					<input type="text" name="address[state]" class="form-control" value="<?php echo $address->state; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Country</label>
				<div class="col-sm-10">
					<input type="text" name="address[country]" class="form-control" value="<?php echo $address->country; ?>">
				</div>
			</div>

			<div class="row mb-3">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Zip Code</label>
				<div class="col-sm-10">
					<input type="text" name="address[zipcode]" class="form-control" value="<?php echo $address->zipcode; ?>">
				</div>
			</div>
			

			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>

	<?php require_once 'view/html/footer.phtml'; ?>
</body>
</html>