<?php $salesmans = $this->salesmans; ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Salesman Grid</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>
<body>

	<?php require_once 'view/html/header.phtml'; ?>

	<div class="container">		
	<div class="d-flex justify-content-between">
		<h3>Manage Salesmans</h3>
		<div class="d-grid gap-2 d-md-flex justify-content-md-end">
	 		<a class="btn btn-outline-primary me-md-2 m-4 mx-0" type="button" href="index.php?c=salesman&a=add">Add Salesman</a>
		</div>
	</div>

	<table class="table table-bordered table-success table-striped w-100">
		<thead>
			<tr>
				<th>Salesman Id</th>
				<th>first_name</th>
				<th>last_name</th>
				<th>email</th>
				<th>gender</th>
				<th>mobile</th>
				<th>company</th>
				<th>Status</th>
				<th>creat_at</th>
				<th>update_at</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<?php foreach ($salesmans as $salesman) : ?>
		<tbody>
			<tr>
				<td><?php echo $salesman->salesman_id; ?></td>
				<td><?php echo $salesman->first_name; ?></td>
				<td><?php echo $salesman->last_name; ?></td>
				<td><?php echo $salesman->email; ?></td>
				<td><?php echo $salesman->gender; ?></td>
				<td><?php echo $salesman->mobile; ?></td>
				<td><?php echo $salesman->company; ?></td>
				<td><?php echo $salesman->getStatusText($salesman->status); ?></td>
				<td><?php echo $salesman->create_at; ?></td>
				<td><?php echo $salesman->update_at; ?></td>
				<td><a href="index.php?c=salesman&a=edit&id=<?php echo $salesman->salesman_id; ?>">Edit</a></td>
				<td><a href="index.php?c=salesman&a=delete&id=<?php echo $salesman->salesman_id; ?>">Delete</a></td>
			</tr>
		</tbody>
		<?php endforeach; ?>
	</table>

	<?php require_once 'view/html/footer.phtml'; ?>
</body>
</html>

